To Clean the dirty data

---

In [1]:
# load the dataset
import pandas as pd
import numpy as np
df = pd.read_csv('/content/dirty_cafe_sales.csv')
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

The dataset is of a cafe sales with 8 coloumns

In [2]:
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [3]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

info() gives the over view of whole data set each coloumn consiste of none null values but as we seen before first five rows of data set the most values of coloumns were filled with "ERRORS" and "UNKNOWN".As we look closely data types of coloumns were mismatched

In [5]:
# to change the data types of coloumns
df['Quantity'] = pd.to_numeric(df['Quantity'],errors = 'coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'],errors = 'coerce')
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'],errors = 'coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'],errors = 'coerce')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'],errors = 'coerce')
df.info() # again info is used to check if data types have changed

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 625.1+ KB

Now the datatypes have been changed by using pandas library now it's time to remove null values

In [6]:
# Replace error and unknown values with nan
df = df.replace({'ERRORS': np.nan, 'UNKNOWN': np.nan, 'ERROR': np.nan})
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [7]:
# fill those null values
df['Item']=df['Item'].fillna('UNKNOWN')
df['Quantity'] = df['Quantity'].fillna(df['Total Spent'] / df['Price Per Unit'])
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])
df['Payment Method'] = df['Payment Method'].fillna('UNKNOWN')
df['Location'] = df['Location'].fillna('UNKNOWN')
df['Transaction Date'] = df['Transaction Date'].fillna('UNKNOWN')
df['Price Per Unit']=df['Price Per Unit'].fillna(df['Quantity'] / df['Total Spent'])
df.dropna(subset=['Quantity','Price Per Unit','Total Spent'], inplace = True)
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.to_csv('cleaned_cafedata')

In [10]:
from google.colab import files

df.to_csv('cleaned_cafedata.csv', index=False)

files.download('cleaned_cafedata.csv')